
// Objective-C API for talking to the following Go packages
//
//	leafy
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Leafy_FRAMEWORK_H__
#define __Leafy_FRAMEWORK_H__

#include "Leafy.objc.h"
#include "Universe.objc.h"

#endif
