// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd9SV9N_1ZEDiBzyVyMH3TEwttkSdDVSw',
    appId: '1:853812438928:android:c49d999ff2c082737fb515',
    messagingSenderId: '853812438928',
    projectId: 'leafy-20346',
    storageBucket: 'leafy-20346.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0ShILR7rKD5Dn3qtOgs7WE3Qjy0fQN0g',
    appId: '1:853812438928:ios:4aa938579894cc477fb515',
    messagingSenderId: '853812438928',
    projectId: 'leafy-20346',
    storageBucket: 'leafy-20346.appspot.com',
    androidClientId: '853812438928-eiat8kq2v33pk2ooiv6g87a6v9guin06.apps.googleusercontent.com',
    iosClientId: '853812438928-2tl812dcap611o1rot1ol44dnpakh7ns.apps.googleusercontent.com',
    iosBundleId: 'com.leafybitcoin.leafy',
  );
}
